# Generated by Django 5.2.6 on 2026-04-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('original_filename', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('file_type', models.CharField(default='pdf', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('overall_score', models.FloatField(default=0)),
                ('matched_skills_json', models.TextField(default='[]')),
                ('missing_skills_json', models.TextField(default='[]')),
                ('resume_skills_json', models.TextField(default='[]')),
                ('required_skills_json', models.TextField(default='[]')),
                ('category', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full-Stack Developer'), ('ml', 'ML/AI Engineer'), ('devops', 'DevOps Engineer'), ('data', 'Data Scientist'), ('mobile', 'Mobile Developer'), ('other', 'Other')], default='other', max_length=20)),
                ('detailed_feedback', models.TextField(blank=True, default='')),
                ('recommendations_json', models.TextField(default='[]')),
                ('strengths_json', models.TextField(default='[]')),
                ('skill_scores_json', models.TextField(default='{}')),
                ('required_scores_json', models.TextField(default='{}')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.resume')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
